apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec: 
      containers:
        - name: pod-user
          image: tutkuince/user-service:v01
          resources:
            limits:
              memory: "2048Mi"
              cpu: "300m"
          ports:
          - containerPort: 9091


